; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:messenger]
platform = espressif32@6.12.0
board = Messenger
framework = arduino
board_build.filesystem = littlefs
upload_protocol = esptool
monitor_filters = esp32_exception_decoder, send_on_enter
monitor_echo = yes
monitor_eol = CRLF
debug_tool = esp-builtin
lib_deps = 
	adafruit/Adafruit TCA8418@^1.0.2
	jgromes/RadioLib@^7.1.2
	mikalhart/TinyGPSPlus@^1.1.0
	
build_flags = 
	-D ARDUINO_USB_MODE=1
	;-D USE_TINYUSB
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D DEBUG
	-D HERMES_VERSION="0.0.0"
	-DBLE_42_FEATURE_SUPPORT=TRUE -DBLE_50_FEATURE_SUPPORT=TRUE
	-DCORE_DEBUG_LEVEL=4
	-D USE_ESP_IDF_LOG
	-D TAG=\"D\"
	-D CONFIG_ESP_NIMBLE_HOST_TASK_STACK_SIZE=8192
	-D CONFIG_ESP_NIMBLE_CONTROLLER_TASK_STACK_SIZE=4096
	;-D GPS_DEBUG
	-D USE_NIMBLE